### ISSUE TITLE
Mac OS X installer pkg bug

### ISSUE THREAD

**Issue by paulbloch** [haskell/haskell-platform#151]
Haskell Platform 2014.2.0.0 for Mac OS X, 64bit 

The bug is that it fails in a command line install with the `installer` command.  The final line of the HaskellPlatform post install script is 

sudo -n -u $USER open /Library/Haskell/doc/start.html

which fails if it isn't a GUI install.  The `installer` command sets the variable COMMAND_LINE_INSTALL so that scripts can tell that it is a command line install.  Opening the documentation should be wrapped with a check for that variable.

Something like:

if [ "${COMMAND_LINE_INSTALL}" == "" ]; then
 sudo -n -u $USER open /Library/Haskell/doc/start.html
fi

**Comment by mzero** [comment]
done with some small notes:

* turns out you have to expressly check against '1', `-z` wasn't enough
* I choose to keep the open command if it was a GUI install, even if done by root - turns out that we used to do this open as root and it wasn't a problem - if it's a GUI install, I'd rather have the page opened.
* there is some echo text about the docs location when it is a command line install - turns out command line installer swallows them - oh well!
