### ISSUE TITLE
Cabal packages of build-type Configure don't build on Windows

### ISSUE THREAD

**Issue by bgamari** [haskell/haskell-platform#179]
Windows doesn't have `autoconf` and friends, which are necessary to build packages of Cabal `build-type: configure` (e.g. `network` as described in #165). This is resolved in [MinGHC](https://github.com/fpco/minghc) by shipping the necessary part of the toolchain from [MSYS](http://www.mingw.org/wiki/MSYS). 

I think it's fair to call this a major bug as Haskell Platform can't claim full Windows suport until this is fixed. We should try to resolve this before the 7.10.2 release if at all possible.

**Comment by randen** [comment]
Fixed in HP 7.10.2 by including the MSys tools.  They are in the top-level of the installation directory, in "msys".  This is the "usr" directory from the git-for-windows PortableGit distro package 2.4.5.1, which is exactly what stack is using at the moment.  The "usr" directory is probably overkill and includes way, way too much.  To avoid PATH pollution (since some of these executables have exactly the same name as some Microsoft Windows executables, such as dir, find, echo, etc. but are different in functionality), the msys directory is *not* put onto the users or system PATH.  To use these tools, the user can manually add this directory to their PATH (probably just temporarily, right before "cabal install" of a package which needs it) or perhaps cabal could be changed to do that step automatically for the user by looking for an "msys" installation in the HP install directory.

**Comment by gbaz** [comment]
Closing in favor of #207
