### ISSUE TITLE
WARNING: cache is out of date: c:/Program Files/Haskell Platform/7.10.2\lib\package.conf.d\package.cache

### ISSUE THREAD

**Issue by thomie** [haskell/haskell-platform#189]
Sven Panne [reports](https://ghc.haskell.org/trac/ghc/ticket/10205#comment:17) that the package.cache is initially out-of-date, after installing GHC 7.10.2 RC2 on Windows:

```
$ ghc-pkg list -v
Timestamp 2015-07-06 19:15:52 UTC for c:/Program Files/Haskell Platform/7.10.2\lib\package.conf.d\package.cache
Timestamp 2015-07-07 07:51:56.8491787 UTC for c:/Program Files/Haskell Platform/7.10.2\lib\package.conf.d (NEWER than cache)
WARNING: cache is out of date: c:/Program Files/Haskell Platform/7.10.2\lib\package.conf.d\package.cache
ghc will see an old view of this package db. Use 'ghc-pkg recache' to fix.
...
```

I think this is a bug in haskell-platform's install script for Windows.

Make sure that the `lib\package.conf.d\package.cache` file is always newer than the `lib\package.conf.d` directory. Either run `ghc-pkg recache` before release, or touch the `package.cache` file.

To verify that this is (most likely) not a bug in GHC's build system, I downloaded and unpacked https://www.haskell.org/ghc/dist/7.10.1/ghc-7.10.1-x86_64-unknown-mingw32.tar.bz2, and compared the timestamps of the cache file and its parent directory:

```
ls lib/package.conf.d/package.cache lib/package.conf.d -d --full-time
drwxr-xr-x 2 thomas thomas    540 2015-03-27 05:41:46.000000000 +0100 lib/package.conf.d/
-rw-r--r-- 1 thomas thomas 120677 2015-03-27 05:41:46.000000000 +0100 lib/package.conf.d/package.cache
```

Since those timestamps are the same, there won't be any problems here.

Edit:
Note that running `ghc-pkg recache` fixes the problem for users, but as Sven reports:

a) You have to do it as an Administrator, which might not be an option for all users.
b) The Windows installer for 7.10rc2 shouldn't install the package DB like this, forcing users to recache as an Administrator directly after installation.

**Comment by 23Skidoo** [comment]
IIRC, HP installer used to run `ghc-pkg recache` a post-install step. Was this removed? 

> You have to do it as an Administrator, which might not be an option for all users.

Note that you have to be Administrator to install HP globally anyway. If you aren't, and you install it somewhere you have write access to, it's not a problem.

**Comment by randen** [comment]
The nsi script, as far as I can tell (and it is more or less the same as it had been, I believe), did not do any post-install step for this.  In the build notes, it says to do a recache but this is pre-build of the installer, so it was on the build side not the installed side.

A post-install invocation of ghc-pkg from the nsi script should be "easy".  I can guess that we didn't see this very often in the past since the emphasis was on the user doing global installs of packages, which would likely have fixed the cache at that point.  Now, the emphasis is on sandboxes, which could cause a user to never end up re-writing the cache.

**Comment by 23Skidoo** [comment]
Looking at https://github.com/23Skidoo/haskell-platform-windows/blob/master/Nsisfile.nsi, it seems like I didn't implement this as a post-install step after all. Should be fairly easy to do.

**Comment by thomie** [comment]
`winOsFromConfig` is supposed to do a `ghc-pkg recache` here:
https://github.com/haskell/haskell-platform/blob/a2fe07c0665b1fa471e97b373fda5979990dee22/hptool/src/OS/Win.hs#L136

**Comment by thomie** [comment]
> In the [build notes](https://github.com/23Skidoo/haskell-platform-windows/blob/e413a1d553d2d0effb6a3bee87698c2ab27d065f/README#L55), it says to do a recache but this is pre-build of the installer, so it was on the build side not the installed side.
Which should also be fine, as long as it is not forgotten. Automation would be better.

**Comment by randen** [comment]
The winOsFromConfig will do the recache for the execution of ghc that happens while building the Haskell libraries which are incorporated (as binaries) into the installers.  I believe the problem noted by this issue is that when we install on the user's machine, the directory package.conf.d will have a newer create date than that of the file package.cache (since we just created the package.conf.d directory during the install, it will have a newer date than the package.cache file that is installed with a create-date-preserving copy).  The fix needed for this is to include in the NSIS script (on Windows, we currently use a tool called NSIS which builds the installer) a step to run after a successful installation that invokes the just-installed ghc-pkg to do the re-cache.
