### ISSUE TITLE
hptool fails to build with

### ISSUE THREAD

**Issue by mainland** [haskell/haskell-platform#196]
When building the 7.10.2 platform from source, I get the error below.

Where is ReleaseFiles.hs?

```
***
*** Building hptool
***
Package has never been configured. Configuring with default flags. If this
fails, please run configure manually.
Resolving dependencies...
Configuring hptool-0.1...
Building hptool-0.1...
Preprocessing executable 'hptool' for hptool-0.1...

src/Website.hs:17:8:
    Could not find module ‘ReleaseFiles’
    Use -v to see a list of the files searched for.
```

**Comment by erantapaa** [comment]
For now you can get it from the repo: 

https://github.com/haskell/haskell-platform/tree/master/hptool/src

**Comment by mzero** [comment]
oops - missing from the .cabal file - will fix ASAP

**Comment by mainland** [comment]
ReleaseFiles.hs is still not in the haskell-platform-7.10.2-a tarball.

**Comment by mzero** [comment]
ugh - build issue... re-built and should be up in a bit.

Question: Do you find working from the source tar ball more useful than working from a clone of this repo? If so, I'd like to understand why - so that either we can make the source tar ball more useful and easier to use - or so that we can make the repo easier to use and eliminate the source tar ball.

**Comment by mainland** [comment]
I have always built GHC and the Haskell platform from tarballs. I have a script that can build any GHC/platform combo, including historic versions. Instead of changing the script to clone a tag, I've stuck with the tarballs.
I have found the tarball perfectly easy to use until this release, due to the missing file.
Thanks for the fix!

**Comment by gbaz** [comment]
ok since this is fixed i guess i'll close...
