### ISSUE TITLE
How about intelligible setup instructions?

### ISSUE THREAD

**Issue by OnkelTem** [haskell/haskell-platform#210]
Sorry for such a curt title, but I really don't get how it is supposed to start using anything by just following the README.md, which at least incomplete.

So I've fetched haskell-platform and typed:

$ ./platform.sh 
```
./platform.sh: 18: ./platform.sh: cabal: not found
***
*** Building hptool
***
./platform.sh: 29: ./platform.sh: cabal: not found
```

Ok, seems like I'm missing cabal. There is not a line in the README about cabal. But there is a reference to certain "bindist" and link to https://www.haskell.org/ghc/download_ghc_7_8_3 where the first block says: stop and get off.

Thanks in advance.

**Comment by gbaz** [comment]
Those instructions are for people _building_ platform distributions.

As an end-user/consumer of the platform, you should follow the instructions at: https://www.haskell.org/platform/

we should perhaps make this markdown more clear.

**Comment by gbaz** [comment]
If you really do want to build from source, then yes, you should install the ghc bindist first. The reason the ghc page says "stop" is precisely because most people shouldn't be using from source, but rather using one of the other methods.

That said, for the latest platform, you'll actually want a newer ghc (https://www.haskell.org/ghc/download_ghc_7_10_2) and we should probably update the readme to indicate this.

**Comment by OnkelTem** [comment]
Thank you for your prompt reply, Gershom!

I'm reading [Learn You a Haskell] (http://learnyouahaskell.com/) book which recommends `haskell-platform` to start with Haskell. And since I'm using outdated Ubuntu 12.04 which offers `haskell-platform` `2012.1.0.0` I found it's reasonable to build from source.

Yeah, I think the README needs some update. Here is how I was reading it:

> "Haskell Platform" is a combination of the GHC compiler and core libraries,
plus additional tools and libraries covering a range of common programming
tasks.

So being a combination of smth. it includes those things, gotcha. Then goes:

> Running the installer is all you need to get a working Haskell environment.

— which further confirms that I don't need anything else except the haskell-platform. Great!
Then follows the REQUIREMENTS FOR BUILDING section:

> You need the platform build files, either from the *source repo* or the *source tarball*

Ok, I'm having them, for I just fetched the repo. Can't wait to read building instructions!
But then suddenly:

> You need a GHC bindist that matches the OS you are compiling on.

Wait. How that's happened that I just had everything for the build and now I'm needing GHC which was declared previously as included? And that word "bindist"... which could that mean? Oh. 
And from bad to worse:

> The machine doing the build needs to have a working Haskell setup: Usually,
GHC (7.4 or later), Cabal (1.16 or later), and haddock and HsColour must be on
the $PATH.

But GHC is the Haskell, isn't it? Then what is the platform if I have to get everything separately and before even start building the platform?

Sorry if I sound stupid. But this all very confusing for me.

**Comment by gbaz** [comment]
I would recommend the generic linux install instead of building your own platform: https://www.haskell.org/platform/#linux-generic

Absent that, _just_ install the current ghc bindist (https://www.haskell.org/ghc/download_ghc_7_10_2) and you're relatively good to go. You can `cabal install` other packages as necessary -- and none should be necessary for just working through the LYAH material.

**Comment by gbaz** [comment]
i  consider this particular issue fixed by the merge.
