### ISSUE TITLE
Haskell platform on Debian is sadly out of date

### ISSUE THREAD

**Issue by nrnrnr** [haskell/haskell-platform#213]
The Haskell Platform for Debian Linux asks users to use APT to install the Haskell Platform.  But the recently released Debian stable distribution (code name jessie) includes a Haskell Platform from 2013.  It would be fantastic to provide a current  Haskell Platform that is compiled against jessie, and who knows, perhaps the Debian people would include in in backports?  But if that doesn't work, there should be another path for people who need or want a current Haskell Platform.

**Comment by gbaz** [comment]
@hvr could maybe extend his ppas to cover the new minimal platform once we get that in place?

**Comment by gbaz** [comment]
@nomeata I take it this is just a consequence of debian moving slow? Do you recommend we try to move to @hvr 's ppas for a minimal platform in the future, or is there a better approach?

**Comment by nomeata** [comment]
Debian stable is stable, not much we can do about this.

I started to provide backports of GHC and `cabal-install` in `jessie-backports`. This is good enough to get people started, even if it is not the full platform.

But `jessie-backports` can only ship what is in Debian testing, so it’s only 7.8 so far. I am waiting for 7.10.3 in order to move that from experimental to sid, from where it can migrate to testing (which can, depending on what issue come up, can take longer than planned). Then I can update the backport to 7.10.

All not very satisfying, I know.

**Comment by gbaz** [comment]
@nomeata do you have any suggestions as to how we could improve the platform download page ( https://www.haskell.org/platform/#linux-debian ) to include more of that information? maybe just to point to jessie-backports?

**Comment by nomeata** [comment]
How about simply this blurb:

Note that Debian may not have the latest and greatest version of the haskell-platform. If that bothers you follow the “generic” instructions.
