### ISSUE TITLE
Install dir ignored on windows silent install

### ISSUE THREAD

**Issue by odk-** [haskell/haskell-platform#223]
I'm trying to silently install HaskellPlatform-7.10.2-a-x86_64-setup on pack of Windows Server machines. Installation needs to be done in specific dir but using /S /D=full_path_here gives no effect. Platform is still installed to default location. Notes: target dir exists and /S worked as there was no installer window.

**Comment by randen** [comment]
The silent install use case is not explicitly supported, as far as I know.  (Some technical details follow here which may only be of interest to the HP maintainers.)  For example, our NSIS script is not specifically set up for it (e.g., the `MessageBox` calls do not set the default option to be used if silent), and I (at least) have never tested it for this use case.  However, NSIS should allow a silent install if the user specifies the /S switch on the command line.  The missing option for the `MessageBox`s means that message boxes can pop up anyway, if the script logic calls for it, regardless of the silent install.  Further, we do seem to be using the correct installation indirection (via $INSTDIR).  So, with a cursory look at this, it is not obvious why the /D switch was not respected.

**Comment by gbaz** [comment]
According to some googling, custom pages are skiped on silent installs. Dunno if its related?

**Comment by randen** [comment]
After looking at this just now, it does seem #244 is an instance of this same thing.  Due to how NSIS "supports" 64-bit installations (by requiring us to fiddle with $INSTDIR in our script rather than NSIS just handling it), this is likely the problem.

This specific issue does have the separate problem I mention above about the dialog which may or may not need to show, which could cause a dialog during a silent install of the top-level installer (note: #244 is not about a silent install of the main installer).  So, this issue and #244 may share characteristics, and while #244 may practically solve this particular issue, this issue is separate for fully supporting a silent install of the main HP installer (i.e., resolving #244 will not fully support silent installs of the main HP installer, unless we allow that big warning about multiple installs of HP to go unnoticed in the silent case).

**Comment by randen** [comment]
With the resolution of #244, this issue can now be resolved, if it is acceptable that the HP installer will *not* be silent if there are any other HP installations detected (i.e., it will pop up a message box to alert the user of this situation).  We could make the installer script not show this alert during a silent install, but due to the way HP is and has been, this would surely cause user troubles (multiple HPs/GHCs, on the user's PATH).

If we had some strategy for upgrading (e.g., upgrading from one GHC version to another, or uninstalling older HPs, or not relying on/changing the PATH at all and make the user choose via a "switcher script", etc.), one could imagine the HP installer implementing that but the existing way is that the user can only have one "usable" HP-installed GHC at a time.

**Comment by gbaz** [comment]
Ok, I'll close this then.
