### ISSUE TITLE
Windows installer doesn't work with custom locations

### ISSUE THREAD

**Issue by gbaz** [haskell/haskell-platform#244]
as per reddit:

"One warning. Just accept the default install location and everything works. The installer does not work correctly with a custom location: it only installs the uninstaller there and everything else into the default location."

**Comment by randen** [comment]
Well, that's annoying.  The multiple embedded installers are either not getting the custom location passed from the command line all the way through (they are getting invoked with the requested path provided as an option, as can be seen while installing with the "Show Details" text) or the variable that the command line sets is not the one getting used by the rest of the installation script.  (We really need to get off of NSIS and use the Microsoft Installer.)

**Comment by gbaz** [comment]
If we want to sort it out with NSIS, #223 may be related.

Otherwise, if the only issue for MSIs was size, it seems like the lesser evil to move to them in the future rather than battle the less "modern" solution.

**Comment by randen** [comment]
(from #223)

After looking at this just now, it does seem #244 is an instance of this same thing [as #223]. Due to how NSIS "supports" 64-bit installations (by requiring us to fiddle with $INSTDIR in our script rather than NSIS just handling it), this is likely the problem. I believe a fix for this issue would be to not set $INSTDIR in the script when run as a silent install (we should be able to detect this).

A question for this 8.0.1 release: this is a regression from earlier HP releases, so should I fix this now? If so, should there be a naming difference to the executable and/or the UI, and if so, what would that be?

**Comment by gbaz** [comment]
It does seem like a regression, and it would be good to get a patch in. I just patched another longstanding OS X issue. That said, I think we shouldn't cut actual new release candidates yet. Rather, let's wait and see what other reports may roll in, etc. and then maybe consider a new release a month or so out to address whatever other outstanding things may emerge too. As is, 8.0.1 seems new enough that this will continue to be for early adopters rather than a mass cutover yet.

**Comment by MichalStaruch** [comment]
@randen 7.10 didn't leave us with empty bin folder, so yeah, it's a regression. I'd even call it serious one, as devs install SDKs in custom path pretty often.

**Comment by gbaz** [comment]
Point taken. Maybe another day or so to see if other bugs emerge, then cut new binaries (if @randen can solve the issue in short order that is)?

On naming differences -- I think we can change the installed executable and the hash without calling it a new "platform" release as it doesn't change the contents, just fixes the installer.

I'd go with a naming scheme that moves from

    HaskellPlatform-8.0.1-full-i386-setup.exe  

to

    HaskellPlatform-8.0.1-full-i386-setup-a.exe  

Unless there are better ideas?

**Comment by gbaz** [comment]
Ok, these are now built and on the website for download.
