### ISSUE TITLE
Windows Silent install

### ISSUE THREAD

**Issue by abndrew82** [haskell/haskell-platform#248]
Trying to set a silent install for user with SCCM, and the documentation states to use /S and /D="Directory"  With these, I still get a popup about specifying a location.  This is with version 8.0.1.  Any information on how to properly get it to completely silently install would be great.

**Comment by randen** [comment]
If the docs actually show using quotes around the directory name, per the NSIS docs (which is the installer we are using), these quotes cannot be there, even when every other program in the world would expect them (e.g., when there are spaces in the path name).

> /D sets the default installation directory ($INSTDIR), overriding InstallDir and InstallDirRegKey. It must be the last parameter used in the command line and must not contain any quotes, even if the path contains spaces. Only absolute paths are supported.

http://nsis.sourceforge.net/Docs/Chapter3.html#installerusageexamples

If the quotes turns out to be the problem, we can use this issue for correcting the docs.

**Comment by abndrew82** [comment]
Thanks for the comment, looking more into this, the product itself does seem to silent install, what is causing the problem is when you first launch the HaskellPlatform-8.0.1 install with the Silent command it asks you where to extract / install the Stack to, the default choice is the %temp% folder.  This pops up even if you have previously installed the stack.

My test was install the stack with ---- Stack-1.1.2-Windows-x86_65-installer.exe /S   with this it installed to %temp% depending on running user, but even after doing that first the first thing the Haskell install brings up is that menu, if you just cancel it the Haskell install continues silently and installs.  

But need to find a way to stop that window from coming up, as it doesn't continue until that is canceled or completed even if it's already on the comp.

Thanks for any assistance.

**Comment by randen** [comment]
OK, thank you for the additional info, which leds me to believe this is just broken now in the 8.0.1-a HP installers.  Fully silent did work at one point and now does not so possibly the last-minute fix we did in the 8.0.1-a build (for #223) broke this?  I will experiement with the installer scripts to see if I can get to the bottom of this.

**Comment by LRSFC-DanJ** [comment]
I've been tasked with installing this software on a classroom full of computers for our Computing course. However when I run HaskellPlatform-8.0.1-minimal-x86_64-setup-a.exe with the /S switch for silent install, I am still prompted with a window asking for a location for the installation of Haskell Stack. Additionally, the default location specified in this window is unsuitable for an All Users installation of the software (it's in the current logged on user's profile folder). Is it simply that I need to specify a /D switch with a location, or is it due to this bug/issue?

Thanks,
Dan Jackson (Lead ITServices Technician)
Long Road Sixth Form College
Cambridge, UK.

**Comment by randen** [comment]
@LRSFC-DanJ, unfortunately, what you are seeing is due to this issue.  The HP installer can use the /D switch but that is only for the other components (i.e., not stack).  Even if the /S switch were passed on to the stack installer, stack would still go to the current user's location.  So, we might need a /D switch for the GHC, et al components and another switch that is passed to stack for where that is to go (or a way to specify to the stack installer to do an "all users" install but not sure it even supports this at the moment).

@LRSFC-DanJ, given your responsibilities, and if I may ask you for your opinion being more informed than mine about such installs, would using the Microsoft Installer (MSI) for our installers be a better fit for large, unattended installations?  Is that expected/normal from vendors?  We want to change things with HP and stack, but we also want to make sure we will be providing the right level of flexibility to actually be what is typical.

For example, I could imagine that with MSI, if we had such a problem in the field, you or I could "hack" the MSI file (e.g., even with MS's Orca tool) to a) add the missing options to stack; or b) remove or make optional stack and handle it separately.  WIth our current NSIS-based installer, I do not believe there is any way to fix or even work-around this issue in the field.  :-(

**Comment by abndrew82** [comment]
I would say going MSI route may make it easier for users in the situation that LRSFC-DanJ and I are in, with having the need to install it on multiples of computers across Campus Labs.  With MSI silent installs tend to be easier and in some cases modifiable.

Thanks

**Comment by LRSFC-DanJ** [comment]
@randen MSI would be excellent for us as we have mechanisms in place which can deploy MSI files very easily (they can be deployed by GPO, and we also have a tool called PDQ Deploy which can deploy them on a one-off basis to single or multiple PCs). Other organisations who use SCCM would also be able to make use of MSIs.

Thanks,
Dan Jackson (Lead ITServices Technician)
Long Road Sixth Form College
Cambridge, UK

**Comment by gfawkes66** [comment]
Has this been resolved? Or has anyone found a work around?

I have to install this on a couple of IT Suites in a school so a manual install isn't an option. I am considering installing an older version (7.10)which seems to work fine, but would prefer the latest.

Thanks

**Comment by gbaz** [comment]
fixed in the new release.

/STACK works with the /S flag to specify a stack location sans popup, and /D with the /S flag to specify a direct ghc/platform location sans popup.

**Comment by randen** [comment]
Tiny clarification, example, and note.

/STACK and /D can be used together as well; they are not mutually exclusive.  For example, this is valid:
`
HaskellPlatform-8.0.2-full-x86_64-setup.exe /S /STACK=c:\path for stack\local\bin /D=c:\Program Files\Haskell\Platform\8.0.2`

Note that the NSIS installer base that we use requires (?) no quotes on paths even with spaces in the path, and the NSIS installer requires the /D (when specified) to be last.
