### ISSUE TITLE
Where to download releases from?

### ISSUE THREAD

**Issue by paulmenzel** [haskell/haskell-platform#253]
The `README` still says GitHub, but the release 8.0.1 is missing [there](https://github.com/haskell/haskell-platform/releases) – where 7.10.3 is the latest release –, but is available at https://haskell.org/platform/download/8.0.1/haskell-platform-8.0.1.tar.gz, which is linked from https://www.haskell.org/platform/#linux-source.

**Comment by gbaz** [comment]
oh dear, we haven't been using that releases thing since a new crew took over! The releases for end-users are at  https://haskell.org/platform/

The releases on that page (which we haven't been updating, thanks for pointing it out) are the source releases for the platform _builder_ as far as I know.

Does that make sense? I guess I can try to update the README.

**Comment by gbaz** [comment]
Ok, both clarified the readme, and cut a release. Closing this now.

**Comment by paulmenzel** [comment]
Thank you for updating the README in commit 7bf60169 (clarify readme).

Regarding the release, I am a little surprised that it has the same version number 8.0.1 as the already published releases. Won’t this cause confusion, that they differ, for example the `README`?

PS: You can add `Fixes: #253` to the bottom of the commit description, and GitHub will close the issue autotmatically.
