### ISSUE TITLE
hptool compilation failed

### ISSUE THREAD

**Issue by davidhoover** [haskell/haskell-platform#263]
I'm trying to update Haskell Platform, and running ./platform.sh gives this error:

src/Config.hs:18:32:
    Module `Development.Shake.Rule' does not export `ShakeValue'

I'm running RHEL6, cabal version is 1.20, ghc is 7.6.3, and Haskell is 2013.2.0.0.  Any clue as to what needs to be done?

**Comment by gbaz** [comment]
Its not clear to me the goal -- are you trying to update the platform on your own box, or to create an installer/package for others?

If the former, you should be able to download the generic linux binary from the platform website, rather than building your own platform.

If the latter, then building from the repo is correct, but I suspect your base setup is too out of date to build the current platform. If that's the path (building a platform package for distribution) that you need to solve, I can give you some suggestions on the easiest way to work up to it -- which would probably be just to install a more recent ghc and cabal binary directly, and build the platform on the basis of those...

**Comment by davidhoover** [comment]
The generic linux binaries are not suitable for our situation.  I'm trying to build haskell for a CentOS 6 linux cluster, installing all the binaries into an arbitrary location (not necessarily /usr/local).  We also need multiple versions to be available.

I've installed ghc version 8.0.1 using the standard 'configure/make/make install' method into a shared location and can activate its use using modules.  I had to install cabal into my home directory, rather than a shared location.  Is there a way to install cabal independently so that it can be activated by modules as well?  I was able to install v1.20, but 1.24 gave very generic errors.

Yes, please give me any tips you have about building Haskell Platform from scratch.

David Hoover
HPC @ NIH

**Comment by gbaz** [comment]
The cabal binary that installs into your home directory should be fully relocatable.

The fact that 1.24 gave errors is not so great -- ideally you'll want something more recent than 1.20 to work with ghc 8. If you tried to compile it with 7.6.3 that may be the issue, as that may be just outside of the support window now. Note there are also prebuilt binaries that should work on the cabal website: https://www.haskell.org/cabal/download.html

Finally, for your setup, once you have ghc and cabal moduleized, all the platform really adds is some further build-tools and prebuilt libraries, which might not be necessary to your use case, to be honest?

Let me know if there's any other advice you need here...

**Comment by davidhoover** [comment]
I managed to update cabal to the latest version 1.24, then tried building haskell platform 2014 using ghc v7.8.4.  

./platform.sh --prefix=/usr/local/apps/haskell/2014

It ended at the same error message:

src/Config.hs:18:32:
    Module ‘Development.Shake.Rule’ does not export ‘ShakeValue’

What does this error mean?  Is the configuration file for haskell incorrect?  Should I even try to install HP 2014?

My attempt to build HP 7.10.3 also failed using cabal 1.24 and ghc 8.0.1:

src/OS/Internal.hs:39:47: error: Not in scope: type variable ‘p’

There is a message that appears as it entiers the building hptool phase:

Package has never been configured. Configuring with default flags. If this
fails, please run configure manually.

How do you manually configure the hptool build?

David

**Comment by gbaz** [comment]
The initial error is due to you building an older version of the source that hasn't been patched to work with a newer shake, and is fixed as so: https://github.com/haskell/haskell-platform/commit/6eb710492839ea0366ef6baf36eeb3ff941f2da8

You should always be building with the latest tag of the repo (in this case 8.0.1), rather than pulling snapshots. To build for older releases, you switch out the release line to point to the older release desired:

https://github.com/haskell/haskell-platform/blob/master/hptool/src/Main.hs#L91

The tooling is really built for people with a bit of familiarity with Haskell to build these distros -- I know its not giving the best out-of-the-box experience.

The "has never been configured" message is fine -- its just an informational notice.

But again, if the end goal is creating modules for ghc and cabal on a cluster, I'd motivate just doing that directly. Note also that you won't need to swap cabals when you swap ghc versions -- just using the latest will work with whatever ghc is in place going back through 7.8 certainly, and maintain the various package-libs for them side-by-side.

If you want to email me directly at gershomb at-the-google-mail-service I could try to help drill into the specific thing you're trying to accomplish. From afar, building old platforms manually for deployment on a cluster doesn't seem like the most straightforward approach.

Also: Note that if you're only trying to build old ones rather than use the generic distributions because those distributions aren't relocatable, it should be easy enough to run some greps over those distros to fix them up to a different custom path.

See https://github.com/haskell/haskell-platform/issues/234 for more discussion.

**Comment by davidhoover** [comment]
I tried compiling from the git repo (branch 8.0.1), using cabal 1.24, a static build of stack, and ghc 8.0.1.  I got this error message:

Error when running Shake build system:
* build-all
* build-source
* build/product/haskell-platform-8.0.2.tar.gz
* build/lists/build.packages
* build/package/alex-3.2.1/deps
Error computing dependencies of alex-3.2.1:
Resolving dependencies...
In order, the following would be installed:
containers-0.5.8.1 (via: QuickCheck-2.9.2) (new version)
directory-1.2.7.0 (latest: 1.3.0.0) (new version)
pretty-1.1.3.4 (via: template-haskell-2.11.0.0) (new version)
primitive-0.6.1.0 (latest: 0.6.2.0) (via: tf-random-0.5) (new package)
random-1.1 (via: QuickCheck-2.9.2 tf-random-0.5) (new package)
template-haskell-2.11.0.0 (via: QuickCheck-2.9.2) (reinstall) (changes: pretty-1.1.3.3 removed)
tf-random-0.5 (via: QuickCheck-2.9.2) (new package)
QuickCheck-2.9.2 (new package)

Warning: The following packages are likely to be broken by the reinstalls:
ghci-8.0.1
ghc-8.0.1
Use --force-reinstalls if you want to install anyway.

CallStack (from HasCallStack):
  error, called at src/Package.hs:79:21 in main:Package

What version of gcc should we be using?  Is there a magic combination of versions that are required?

David

**Comment by gbaz** [comment]
There's no problem with the version of gcc here. The issue is that you're building a platform for 8.0.1 but using a tarball, apparently, from 8.0.2

So the haskell platform tool built correctly. The error you're encountering is in the _run_ step, where the 8.0.2 tarball is unpacked by the tool, and trying to build a set of compatible libraries. But the versions are pinned to libraries shipped with 8.0.2, not with 8.0.1.

**Comment by davidhoover** [comment]
What tarball?  Do you mean the GHC tarball?  The GHC tarball I downloaded is from https://www.haskell.org/ghc/download_ghc_8_0_1 <https://www.haskell.org/ghc/download_ghc_8_0_1>, specifically http://downloads.haskell.org/~ghc/8.0.1/ghc-8.0.1-x86_64-centos67-linux.tar.xz <http://downloads.haskell.org/~ghc/8.0.1/ghc-8.0.1-x86_64-centos67-linux.tar.xz>.

How do I explicitly determine the version of the tarball?  Can you point me to links for the correct assembly of versions?  Should I be checking out a specific tag or branch from the git repo?

David

**Comment by gbaz** [comment]
Ah, I misread the error. The opposite issue is occurring and somehow the hptool is trying to build a _newer_ release. If you look at https://github.com/haskell/haskell-platform/blob/8.0.1/hptool/src/Main.hs#L91 you'll see that the release is set to 8_0_1

But the build error is pointing to trying, I guess to build 8.0.2 as you can see. If your main file there reads 8_0_2 instead of 8_0_1 then you're still trying to build from head i guess, and not the 8_0_1 tag.
