### ISSUE TITLE
Platform 8.2.2 doesn't install on Windows 10

### ISSUE THREAD

**Issue by jtod** [haskell/haskell-platform#299]
After installing 8.2.2 on Win 10 (on two different machines), launching ghci in a cygwin bash shell produces this:

GHCi, version 8.2.2: http://www.haskell.org/ghc/  :? for help
<command line>: user specified .o/.so/.DLL could not be loaded (addDLL: pthread or dependencies not loaded. (Win32 error 193))
Whilst trying to load:  (dynamic) pthread
Additional directories searched: (none)

A 64 bit version of Haskell Platform has never worked on any Windows machine I've tried; the last version that did work was 8.0.1 (32 bit).

**Comment by gbaz** [comment]
@jtod are you running a 32 bit windows (or a 32 bit cygwin)? in the former case then the 64 bit won't work, in the latter I suspect it will be problematic as well :-/

Unfortunately we haven't had 32 bit releases lately due to various issues with ghc support. We're hoping to fix them in the new release -- but we'll see.

If you've got 32 bit cygwin executables but a 64 bit OS, does launching ghci from a different sort of shell (e.g. just `cmd`) help at all?

**Comment by gbaz** [comment]
(note: this is likely not a platform issue, but just an issue with the ghc bindist itself)

**Comment by jtod** [comment]
Thanks, gbaz.  It is 64 bit windows, and 64 bit cygwin I believe.  I've also tried running ghci on emacs shell, and Windows powershell; it doesn't work on either of them.  I tried command prompt too; ghci starts up there, but cabal doesn't work in command prompt.

**Comment by 23Skidoo** [comment]
Using Cygwin with GHC or `cabal-install` usually results in brokenness, try the MSYS shell instead.

**Comment by jtod** [comment]
Do you mean msys2.exe, or mingw64.exe, or mingw32.exe, all in C:\Program Files\Haskell Platform\8.2.2\msys?  All three of those crash on launch.

**Comment by gbaz** [comment]
@23Skidoo the brokenness with cygwin historically came from configure type builds iirc. Nowadays if the extra-prog-path  extra-lib-dirs  and extra-include-dirs are set to point to mingw stuff, then it should work from a cygwin shell as well...

This looks like something else entirely as far as I can tell. Unfortunately I don't have a good win10 instance to test with :-/. I hate to burden @Mistuke but that's our go-to expert on win weirdness. One thing to try is to see if this problem occurs with the choco packages too (https://chocolatey.org/packages/ghc/8.2.2) or if there's something more specific going on.

**Comment by Mistuke** [comment]
It likely will fail. I think he's running into an issue with how `newlib` based code shares the runtime between processes. His initial error is likely because his Cygwin installation contains a `libpthread`. GHC 8.2 is unable to force dependencies of it's dependencies from certain subdirectories so GHC is likely picking up this library. GHC 8.4 should be more hardened against this but I'm not sure since I haven't tested it on Cygwin.

To verify this, run in your Cygwin run `strace ghc --interactive`. and paste the result here. This will likely show it's picking up and trying to load a dependency from your Cygwin install instead of the GHC bindist.
`msys2` likely crashes because you globally have Cygwin on your path likely or a Cygwin process running when you try to run it.  Mixing Cygwin and MSYS2 is very temperamental and never recommended, see under the `PATH` section here https://github.com/msys2/msys2/wiki/MSYS2-introduction

**Comment by jtod** [comment]
The strace result is copied below:  One other thing - ghc-pkg check produces lots of lines like the following.  I haven't been able to find any mention of 8.0.1 in my config files, but it has to be there somewhere.  Does that look like a problem?

> Warning: dynamic-library-dirs: C:\Program Files\Haskell Platform\8.0.1\mingw\lib doesn't exist or isn't a directory
> Warning: include-dirs: C:\Program Files\Haskell Platform\8.0.1\mingw\include doesn't exist or isn't a directory
> Warning: dynamic-library-dirs: C:\Program Files\Haskell Platform\8.2.2\lib\extralibs\x86_64-windows-ghc-8.2.2 doesn't exist or isn't a directory

-- Thanks, John

$ strace ghc --interactive
GHCi, version 8.2.2: http://www.haskell.org/ghc/  :? for help
<command line>: user specified .o/.so/.DLL could not be loaded (addDLL: pthread or dependencies not loaded. (Win32 error 193))
Whilst trying to load:  (dynamic) pthread
Additional directories searched: (none)
$

**Comment by Mistuke** [comment]
hmm, the output of Cygwin's strace is really not useful... then things get a little harder (ps. are you sure you can't run msys2 after closing every single instance of Cygwin and any Cygwin utilities you have have running?)

Error 193 indicate it's something like what @gbaz said before. But the program is clearly running.. since strace isn't working the only other way I know of to get the information is by turning on loader snaps.

For that you need to get the debugging tools for windows https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/ (follow the instructions for `As a standalone tool set`).

After it's installed, in start open `gflags (x64)` go to `image` type in `ghc.exe` and press `tab`. the options will then be enabled. Check the box next to `Show loader snaps` and press apply.

Now download `DebugView` https://docs.microsoft.com/en-us/sysinternals/downloads/debugview and open it and make sure capturing is started. (Go to the `Capture` menu make sure the option is checked).

Then back in Cygwin run `ghc --interactive` again. and stop capturing. The window should contain a bunch of entries with `LDR` in it. paste the output in a gist and link it back here.

This should tell you exactly why it's failing.

Afterwards in `gflags` uncheck the loader snaps and press `OK` to clear it and exist gflags.
