### ISSUE TITLE
Haskell platform size

### ISSUE THREAD

**Issue by cup** [haskell/haskell-platform#326]
Haskell platform size

I went to this page:

https://haskell.org/platform/windows.html

and I discovered that the download is 268 MB. This was surprising to me, so I
looked at other languages:

Language | Size   | Link
---------|--------|-----
Go       | 118 MB | https://golang.org/dl
Perl     | 102 MB | http://strawberryperl.com/releases.html
R        | 80 MB  | https://cran.cnr.berkeley.edu/bin/windows/base
Julia    | 50 MB  | https://julialang.org/downloads
Python   | 25 MB  | https://python.org/downloads/release/python-373
PHP      | 25 MB  | https://windows.php.net/download
D        | 23 MB  | https://dlang.org/download.html
Ruby     | 11 MB  | https://rubyinstaller.org/downloads

So Haskell is more than double the size of Go. Or to put another way, Haskell
is larger than R, Julia, Python, PHP, D and Ruby **combined**. Can anything be
done about this or is the large size unavoidable?

**Comment by gbaz** [comment]
The platform installer certainly can't do anything about this, since it just packages up components from ghchq. I think in general this is just the way things are -- there's not just an interpreter and compiler, but a large number of prebuilt core libraries, each of which have all their profiling and debugging info included. So those take the size they take.
